# Generated by Django 6.0.3 on 2026-03-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Problema',
                'verbose_name_plural': 'Tipos de Problemas',
            },
        ),
        migrations.AddField(
            model_name='taskevidence',
            name='materiais_utilizados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskevidence',
            name='tempo_gasto',
            field=models.CharField(blank=True, help_text='Ex: 2 horas, 30 minutos', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskevidence',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evidences/'),
        ),
        migrations.AddField(
            model_name='task',
            name='tipo_problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tasks.tipoproblem'),
        ),
    ]
