# Generated by Django 6.0.3 on 2026-04-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tipo_problema',
        ),
        migrations.RemoveField(
            model_name='taskevidence',
            name='materiais_utilizados',
        ),
        migrations.RemoveField(
            model_name='taskevidence',
            name='tempo_gasto',
        ),
        migrations.DeleteModel(
            name='AreaPredio',
        ),
        migrations.DeleteModel(
            name='TipoProblem',
        ),
    ]
