# Generated by Django 6.0.3 on 2026-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_assigned_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevidence',
            name='photo',
            field=models.ImageField(default='', upload_to='evidences/'),
            preserve_default=False,
        ),
    ]
