# Generated by Django 6.0.3 on 2026-05-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_cnpj_userprofile_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
    ]
