# Generated by Django 6.0.6 on 2026-06-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tab_session_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tabsession',
            new_name='tab_session_tab_id_483c82_idx',
            old_name='tab_session_tab_id_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tabsession',
            new_name='tab_session_user_id_df36d9_idx',
            old_name='tab_session_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tabsession',
            new_name='tab_session_expires_9d9f5b_idx',
            old_name='tab_session_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='tabsessionlog',
            new_name='tab_session_tab_ses_f5d39b_idx',
            old_name='tab_session_log_tab_session_created_at_idx',
        ),
    ]
